name: faceapi
server:
  port: 8043
  context-path: /faceapi
  session:
    timeout: 1000000
#  ssl:
#    key-store: wx.linktoyl.com.jks
#    key-password: linktoyl
#    key-store: wx.vitco.cn.jks
#    key-password: vitco2017
#    key-store-type: JKS
  tomcat:
    max-connections: 2000
    max-threads: 2000
  connection-timeout: 60000

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.vitco.stface.entity

spring: 
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  # profiles:
  # active: dev
  datasource:
      url: jdbc:mysql://47.93.234.168:3306/facedemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
      #url: jdbc:mysql://192.168.13.73:3306/cqybgsl_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 212223
      #driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource

  
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true
      max-file-size: 30Mb
      max-request-size: 30Mb

